name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # 매일 UTC 기준 09:00 (한국 시간 18:00)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GH_PAT }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: submissions
          verbose: true
          commit-header: "[LeetCode Sync]"
